### ISSUE TITLE
Add comparison of the results after gzip

### ISSUE THREAD

**Issue by kizu** [eGavr/cmb#6]
We should look how the initial non-minified css gzips, then gzip the result of each minifier, to see the profit after the gzip for each one.

**Comment by tadatuta** [comment]
:+1:

**Comment by eGavr** [comment]
Good idea!

But what archiver to use? `gzip` or, maybe, [zopfli](https://code.google.com/p/zopfli/), or both?

**Comment by kizu** [comment]
I guess both would be perfect — it is better to have more data than less. However, it won't hurt to add an option to CLI, so you could disable archivers at all or use only one (when you'll need to compare things faster).

**Comment by kizu** [comment]
However, right now it would be enough to just use the config file, as you can remove/add things there if you need, and CLI options would be handy somewhere in future, but that's entirely another issue :)

**Comment by eGavr** [comment]
Okey! I'll add the using of archivers to the config file.

**Comment by eGavr** [comment]
I haven't committed it yet, because there are some drawback, but you can already see the result with `gzip` in the club.

**Comment by eGavr** [comment]
Check it!)
